# ###############################################################################
# This file is part of HHsuite workflow.                                        #
#                                                                               #
# Authors: Geoffrey Hutinet and Remi Denise                                     #
# Copyright © 2022 University Coole Cork (Cork, Ireland).                       #
# See the COPYRIGHT file for details.                                           #
#                                                                               #
# HHsuite workflow is a Snakemake workflow run hhsuite and do a visualization   #
# of the similarity between the different profiles.                             #
#                                                                               #
# HHsuite workflow is free software: you can redistribute it and/or modify      #
# it under the terms of the Affero GNU General Public License as published by   #
# the Free Software Foundation, either version 3 of the License,                #
# or (at your option) any later version.                                        #
#                                                                               #
# HHsuite workflow is distributed in the hope that it will be useful, but       #
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY    #
# or FITNESSFOR A PARTICULAR PURPOSE. See the Affero GNU General Public License #
# for more details.                                                             #
#                                                                               #
# You should have received a copy of the Affero GNU General Public License      #
# along with sORTholog (COPYING file).                                          #
# If not, see <https://www.gnu.org/licenses/>.                                  #
# ###############################################################################

##########################################################################
##########################################################################
##
##                            Singularity
##
##########################################################################
##########################################################################
# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity


container: "docker://continuumio/miniconda3"


from snakemake.utils import min_version

# set minimum snakemake version
min_version("6.14.0")

##########################################################################
##########################################################################
##
##                                Rules
##
##########################################################################
##########################################################################


# load config
configfile: "config/config.yaml"


# Path to report rst file
report: "report/workflow.rst"


# Set local rule that could be launch without submiting to cluster because ultra quick
localrules:
    all,


##########################################################################
# Load rules
##########################################################################


include: "rules/common.smk"
include: "rules/hhsuite.smk"
include: "rules/plots.smk"
include: "rules/hmmer.smk"


##########################################################################
##########################################################################


rule all:
    input:
        plots=get_final_output(),
    log:
        os.path.join(OUTPUT_FOLDER, "logs", "all.log"),


##########################################################################
##########################################################################
