restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60

# snakemake settings I like
use-conda: True
jobs: 5
rerun-incomplete: True
printshellcmds: True
resources: [cpus=15, mem_mb=120000]
